interface GeneratedObjectLiteralInterface_1 {
  //SplashAdView
  splashAdView: string;

  //BannerAdView
  bannerAdView: string;

  //NativeAdView
  nativeAdView: string;

  //DrawFeedAdView
  drawFeedAdView: string;
}

export default class FlutterunionadViewConfig {
  public static readonly adevent = "com.gstory.flutter_unionad/adevent";
  
  // View 相关配置
  public static readonly view: GeneratedObjectLiteralInterface_1 = {
    //SplashAdView
    splashAdView: "com.gstory.flutter_unionad/SplashAdView",
    //BannerAdView
    bannerAdView: "com.gstory.flutter_unionad/BannerAdView",
    //NativeAdView
    nativeAdView: "com.gstory.flutter_unionad/NativeAdView",
    //DrawFeedAdView
    drawFeedAdView: "com.gstory.flutter_unionad/DrawFeedAdView"
  };
}