export default class FlutterunionadViewConfig {
  public static readonly adevent = "com.gstory.flutter_unionad/adevent";
  //SplashAdView
  public static readonly splashAdView = "com.gstory.flutter_unionad/SplashAdView"
  //BannerAdView
  public static readonly bannerAdView = "com.gstory.flutter_unionad/BannerAdView"
  //NativeAdView
  public static readonly nativeAdView = "com.gstory.flutter_unionad/NativeAdView"
  //DrawFeedAdView
  public static readonly drawFeedAdView = "com.gstory.flutter_unionad/DrawFeedAdView"
}